repos:
- repo: local
  hooks:
  - id: terraform-test
    name: Run Terraform unit tests
    language: system
    entry: terraform test -filter=tests/unit-tests.tftest.hcl -v
    pass_filenames: false
    always_run: true