name: 'Terraform_Test'

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform-test:
    name: 'Terraform_Test'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    # terraform-docs
    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "true"

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3.0.0
      with:
        cli_config_credentials_token: ${{ secrets.TFE_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
    - name: Terraform Test
      run: terraform test -cloud-run=${{ vars.MODULE_SOURCE }}
      env:
        TFE_TOKEN: ${{ secrets.TF_API_TOKEN }}
